package chess

import "strings"

// CommentItemKind identifies the kind of item inside a PGN comment block.
type CommentItemKind int

const (
	// CommentText is plain text inside a PGN comment block.
	CommentText CommentItemKind = iota
	// CommentCommand is a command annotation like [%clk 0:05:00].
	CommentCommand
)

// CommentItem is one ordered item inside a PGN comment block.
type CommentItem struct {
	Kind  CommentItemKind
	Text  string
	Key   string
	Value string
}

// CommentBlock represents one PGN {...} block.
type CommentBlock struct {
	Items []CommentItem
}

// A MoveTag represents a notable consequence of a move.
type MoveTag uint16

const (
	// KingSideCastle indicates that the move is a king side castle.
	KingSideCastle MoveTag = 1 << iota
	// QueenSideCastle indicates that the move is a queen side castle.
	QueenSideCastle
	// Capture indicates that the move captures a piece.
	Capture
	// EnPassant indicates that the move captures via en passant.
	EnPassant
	// Check indicates that the move puts the opposing player in check.
	Check
	// Null indicates that the move flips the side to move without moving
	// any piece. Null moves are encoded as "Z0" in PGN and "0000" in UCI.
	// They are never generated by ValidMoves and must be inserted
	// explicitly via Game.NullMove or Game.UnsafeMove.
	Null
)

// NewNullMove returns a Move that flips the side to move without moving any
// piece. The returned move carries the Null MoveTag and has no origin,
// destination, or promotion. Null moves must be inserted via Game.NullMove
// or Game.UnsafeMove; they are rejected by Game.Move because they are never
// part of a position's legal moves.
func NewNullMove() Move {
	return Move{tags: Null}
}

// NewMove returns a Move from origin square s1 to destination square s2.
// The optional promo argument supplies a promotion piece type; when omitted
// the move has no promotion. Tags default to none.
//
// The constructor does not attempt to infer Capture or Check tags because
// those depend on the position context (the piece on s1, the occupant of s2,
// and whether the move leaves the opponent in check). Use Position.IsLegal
// or Game.Move to obtain a fully tagged canonical Move when the position is
// known.
func NewMove(s1, s2 Square, promo ...PieceType) Move {
	var p PieceType
	if len(promo) > 0 {
		p = promo[0]
	}
	return Move{s1: s1, s2: s2, promo: p}
}

// A Move is the movement of a piece from one square to another.
type Move struct {
	tags  MoveTag
	s1    Square
	s2    Square
	promo PieceType
}

// String returns a string useful for debugging. String doesn't return
// algebraic notation.
func (m Move) String() string {
	return m.s1.String() + m.s2.String() + m.promo.String()
}

// S1 returns the origin square of the move.
func (m Move) S1() Square {
	return m.s1
}

// S2 returns the destination square of the move.
func (m Move) S2() Square {
	return m.s2
}

// Promo returns promotion piece type of the move.
func (m Move) Promo() PieceType {
	return m.promo
}

// HasTag returns true if the move contains the MoveTag given.
func (m Move) HasTag(tag MoveTag) bool {
	return (tag & m.tags) > 0
}

// WithTag returns a copy of the move with the given MoveTag added.
func (m Move) WithTag(tag MoveTag) Move {
	m.tags |= tag
	return m
}

// MoveNode is one occurrence of a move in a game's move tree.
type MoveNode struct {
	move          Move
	parent        *MoveNode
	tree          *MoveTree
	children      []*MoveNode
	number        uint
	nags          []string
	commentBlocks []CommentBlock
}

// Move returns the move value for this move node.
func (n *MoveNode) Move() Move {
	if n == nil {
		return Move{}
	}
	return n.move
}

func (n *MoveNode) GetCommand(key string) (string, bool) {
	if n == nil {
		return "", false
	}
	for i := len(n.commentBlocks) - 1; i >= 0; i-- {
		block := n.commentBlocks[i]
		for j := len(block.Items) - 1; j >= 0; j-- {
			item := block.Items[j]
			if item.Kind == CommentCommand && item.Key == key {
				return item.Value, true
			}
		}
	}
	return "", false
}

func (n *MoveNode) SetCommand(key, value string) {
	if n == nil {
		return
	}
	for blockIdx := len(n.commentBlocks) - 1; blockIdx >= 0; blockIdx-- {
		for itemIdx := len(n.commentBlocks[blockIdx].Items) - 1; itemIdx >= 0; itemIdx-- {
			item := &n.commentBlocks[blockIdx].Items[itemIdx]
			if item.Kind == CommentCommand && item.Key == key {
				item.Value = value
				return
			}
		}
	}
	if len(n.commentBlocks) == 0 {
		n.commentBlocks = append(n.commentBlocks, CommentBlock{})
	}
	last := len(n.commentBlocks) - 1
	n.commentBlocks[last].Items = append(n.commentBlocks[last].Items, CommentItem{
		Kind:  CommentCommand,
		Key:   key,
		Value: value,
	})
}

func (n *MoveNode) SetComment(comment string) {
	if n == nil {
		return
	}
	if comment == "" {
		n.commentBlocks = nil
		return
	}
	n.commentBlocks = []CommentBlock{{Items: []CommentItem{{Kind: CommentText, Text: comment}}}}
}

func (n *MoveNode) AddComment(comment string) {
	if n == nil || comment == "" {
		return
	}
	if len(n.commentBlocks) == 0 {
		n.commentBlocks = []CommentBlock{{Items: []CommentItem{{Kind: CommentText, Text: comment}}}}
		return
	}
	lastBlock := len(n.commentBlocks) - 1
	for i := len(n.commentBlocks[lastBlock].Items) - 1; i >= 0; i-- {
		item := &n.commentBlocks[lastBlock].Items[i]
		if item.Kind == CommentText {
			item.Text += comment
			return
		}
	}
	n.commentBlocks[lastBlock].Items = append(n.commentBlocks[lastBlock].Items, CommentItem{Kind: CommentText, Text: comment})
}

func (n *MoveNode) Comments() string {
	if n == nil {
		return ""
	}
	return flattenCommentText(n.commentBlocks)
}

// CommentBlocks returns a defensive copy of the move node's structured PGN comment blocks.
func (n *MoveNode) CommentBlocks() []CommentBlock {
	if n == nil {
		return nil
	}
	return copyCommentBlocks(n.commentBlocks)
}

// NAGs returns a defensive copy of the move node's numeric annotation glyphs in
// their canonical "$N" form, in the order they were added.
func (n *MoveNode) NAGs() []string {
	if n == nil {
		return nil
	}
	return append([]string(nil), n.nags...)
}

// SetNAGs replaces all of the move node's NAGs. Each value is normalised via
// ParseNAG. The replacement is all-or-nothing: if any value is malformed the
// node is left unchanged and the error is returned.
func (n *MoveNode) SetNAGs(nags []string) error {
	if n == nil {
		return nil
	}
	normalised := make([]string, 0, len(nags))
	for _, nag := range nags {
		parsed, err := ParseNAG(nag)
		if err != nil {
			return err
		}
		normalised = append(normalised, parsed)
	}
	n.nags = normalised
	return nil
}

// AddNAG normalises and appends a single NAG to the move node. Order is
// preserved. A malformed value leaves the node unchanged.
func (n *MoveNode) AddNAG(nag string) error {
	if n == nil {
		return nil
	}
	parsed, err := ParseNAG(nag)
	if err != nil {
		return err
	}
	n.nags = append(n.nags, parsed)
	return nil
}

func (n *MoveNode) Parent() *MoveNode {
	if n == nil {
		return nil
	}
	return n.parent
}

// Position returns the position reached by playing this node's move from
// its parent's position. It saves and restores the tree's active cursor so
// the read is observationally pure under ADR-016's single-active-cursor
// invariant. See ADR-018 for the lazy-position design.
func (n *MoveNode) Position() *Position {
	if n == nil || n.tree == nil {
		return nil
	}
	defer n.tree.setCurrent(n.tree.current)
	n.tree.setCurrent(n)
	return n.tree.pos.copy()
}

func (n *MoveNode) Children() []*MoveNode {
	if n == nil {
		return nil
	}
	return append([]*MoveNode{}, n.children...)
}

// ChildrenIter returns an allocation-free iterator over the continuations.
func (n *MoveNode) ChildrenIter(yield func(*MoveNode) bool) {
	if n == nil {
		return
	}
	for _, continuation := range n.children {
		if !yield(continuation) {
			return
		}
	}
}

func (n *MoveNode) Number() int {
	if n == nil {
		return 0
	}
	ret := int(n.number)
	if ret == 0 {
		ret = 1
	}
	return ret
}

// FullMoveNumber returns the full move number (increments after Black's move).
func (n *MoveNode) FullMoveNumber() int {
	return n.Number()
}

// Ply returns the half-move number (increments every move). For the synthetic
// root it returns 0; otherwise it equals the depth of the parent chain from
// n up to (not including) the synthetic root.
func (n *MoveNode) Ply() int {
	if n == nil || n.parent == nil {
		return 0
	}
	depth := 0
	for cur := n; cur != nil && cur.parent != nil; cur = cur.parent {
		depth++
	}
	return depth
}

func (n *MoveNode) addCommentBlock(block CommentBlock) {
	if n == nil || len(block.Items) == 0 {
		return
	}
	n.commentBlocks = append(n.commentBlocks, block)
}

func (n *MoveNode) hasAnnotations() bool {
	return n != nil && (len(n.commentBlocks) > 0 || len(n.nags) > 0)
}

func (n *MoveNode) clone() *MoveNode {
	if n == nil {
		return nil
	}
	ret := &MoveNode{
		move:          n.move,
		number:        n.number,
		nags:          append([]string(nil), n.nags...),
		commentBlocks: copyCommentBlocks(n.commentBlocks),
	}
	for _, child := range n.children {
		childClone := child.clone()
		childClone.parent = ret
		ret.children = append(ret.children, childClone)
	}
	return ret
}

func flattenCommentText(blocks []CommentBlock) string {
	var comments []string
	for _, block := range blocks {
		var blockText strings.Builder
		for _, item := range block.Items {
			if item.Kind == CommentText {
				blockText.WriteString(item.Text)
			}
		}
		if blockText.Len() > 0 {
			comments = append(comments, blockText.String())
		}
	}
	return strings.Join(comments, " ")
}

func copyCommentBlocks(src []CommentBlock) []CommentBlock {
	blocks := make([]CommentBlock, len(src))
	for i, block := range src {
		blocks[i].Items = append([]CommentItem(nil), block.Items...)
	}
	return blocks
}
