name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      - name: Test
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      # A lot of work to get this working and a lot of rewriting of the codebase. Will be added later.
      #- name: Lint
      #  uses: golangci/golangci-lint-action@v3
      #  with:
      #    version: latest

      - name: Generate coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Vulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: Check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Generate changelog
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Go Report Card
        uses: creekorful/goreportcard-action@v1.0
